resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: default-route-openshift-image-registry.apps.ocp-55000351na-ooqg.cloud.techzone.ibm.com/edge-images/ieam-edge-app
  newTag: v0.0.7
