apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: event-listener-ieam-app
  namespace: edge-pipeline
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: ClusterTriggerBinding
          ref: github-release
      template:
        ref: trigger-template-ieam-edge-pipeline
