apiVersion: triggers.tekton.dev/v1alpha1
kind: ClusterTriggerBinding
metadata:
  name: github-release
spec:
  params:
    - name: releaseversion
      value: $(body.release.tag_name)
    - name: gitrepositoryurl
      value: $(body.repository.url)
    - name: contenttype
      value: $(header.Content-Type)
    - name: action
      value: $(body.action)
