apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  creationTimestamp: '2023-06-22T20:21:30Z'
  generation: 24
  labels:
    app.kubernetes.io/instance: ieam-edge-cluster-demo
    app.kubernetes.io/name: ieam-edge-cluster-demo
    operator.tekton.dev/operand-name: openshift-pipelines-addons
    pipeline.openshift.io/strategy: docker
    pipeline.openshift.io/type: kubernetes
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/name': {}
            'f:operator.tekton.dev/operand-name': {}
            'f:pipeline.openshift.io/strategy': {}
            'f:pipeline.openshift.io/type': {}
        'f:spec':
          .: {}
          'f:finally': {}
          'f:params': {}
          'f:resources': {}
          'f:tasks': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
      time: '2023-06-23T06:41:59Z'
  name: ieam-edge-cluster-demo
  namespace: images
  resourceVersion: '7421685'
  uid: 5be52a19-a380-4bdf-beea-400ab560959b
spec:
  params:
    - default: ieam-edge-cluster-demo
      name: APP_NAME
      type: string
    - default: >-
        https://github.com/Client-Engineering-Industry-Squad-1/ieam-edge-cluster-demo
      name: GIT_REPO
      type: string
    - default: main
      name: GIT_REVISION
      type: string
    - default: docker.io/jennuineness/ieam-edge-app
      name: IMAGE_BASE
      type: string
    - default: .
      name: PATH_CONTEXT
      type: string
    - default: latest
      name: IMAGE_VERSION
      type: string
    - name: WEBHOOK_ACTION
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      when:
        - input: released
          operator: in
          values:
            - $(params.WEBHOOK_ACTION)
      workspaces:
        - name: output
          workspace: workspace
    - name: build
      params:
        - name: IMAGE
          value: '$(params.IMAGE_BASE):$(params.IMAGE_VERSION)'
        - name: TLSVERIFY
          value: 'false'
        - name: CONTEXT
          value: $(params.PATH_CONTEXT)
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: buildah
      when:
        - input: released
          operator: in
          values:
            - $(params.WEBHOOK_ACTION)
      workspaces:
        - name: source
          workspace: workspace
    - name: deploy
      params:
        - name: HOST
          value: 150.238.132.77
        - name: USERNAME
          value: itzuser
        - name: PORT
          value: '2223'
        - name: SSH_SCRIPT
          value: >-
            #! /bin/bash


            sh ieam-edge-cluster-demo/deploy/deploy.sh $(params.IMAGE_BASE)
            $(params.IMAGE_VERSION)
        - name: USE_INSECURE_CIPHER
          value: 'false'
      runAfter:
        - build
      taskRef:
        kind: Task
        name: remote-ssh-commands
      when:
        - input: released
          operator: in
          values:
            - $(params.WEBHOOK_ACTION)
      workspaces:
        - name: credentials
          workspace: credentials
  workspaces:
    - name: workspace
    - name: credentials
