kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: workspace-pvc
  namespace: openshift-pipelines
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: managed-nfs-storage
  volumeMode: Filesystem

---

kind: Secret
apiVersion: v1
metadata:
  name: docker-registry
  namespace: openshift-pipelines
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJhcHBpbWFnZSIsInBhc3N3b3JkIjoiM0N5dnohLTZzcWlMUHlibnU5OUIydSIsImF1dGgiOiJZWEJ3YVcxaFoyVTZNME41ZG5vaExUWnpjV2xNVUhsaWJuVTVPVUl5ZFE9PSIsImVtYWlsIjoiIn19fQ==
type: kubernetes.io/dockerconfigjson
