kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: workspace-pvc
  namespace: openshift-pipelines
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: managed-nfs-storage
  volumeMode: Filesystem

