apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  creationTimestamp: '2023-06-22T22:40:55Z'
  generation: 8
  managedFields:
    - apiVersion: triggers.tekton.dev/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:params': {}
          'f:resourcetemplates': {}
      manager: Mozilla
      operation: Update
      time: '2023-06-23T06:39:37Z'
  name: trigger-template-ieam-edge-cluster-demo-1vnor9
  namespace: images
  resourceVersion: '7419371'
  uid: af73e5ee-f143-4404-8ca5-d555a09e453a
spec:
  params:
    - name: releaseversion
    - name: gitrepositoryurl
    - name: contenttype
    - name: action
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        annotations:
          pipeline.openshift.io/started-by: 'kube:admin'
        generateName: ieam-edge-cluster-demo-
        labels:
          app.kubernetes.io/instance: ieam-edge-cluster-demo
          app.kubernetes.io/name: ieam-edge-cluster-demo
          operator.tekton.dev/operand-name: openshift-pipelines-addons
          pipeline.openshift.io/strategy: docker
          pipeline.openshift.io/type: kubernetes
          tekton.dev/pipeline: ieam-edge-cluster-demo
        namespace: images
      spec:
        params:
          - name: APP_NAME
            value: ieam-edge-cluster-demo
          - name: GIT_REPO
            value: >-
              https://github.com/Client-Engineering-Industry-Squad-1/ieam-edge-cluster-demo
          - name: GIT_REVISION
            value: main
          - name: IMAGE_BASE
            value: docker.io/jennuineness/ieam-edge-app
          - name: PATH_CONTEXT
            value: .
          - name: IMAGE_VERSION
            value: $(tt.params.releaseversion)
          - name: WEBHOOK_ACTION
            value: $(tt.params.action)
        pipelineRef:
          name: ieam-edge-cluster-demo
        resources: []
        status: null
        workspaces:
          - name: workspace
            persistentVolumeClaim:
              claimName: pvc-b5c7693e94
          - name: credentials
            secret:
              secretName: remote-ssh-secret
