apiVersion: triggers.tekton.dev/v1alpha1
kind: ClusterTriggerBinding
metadata:
  name: github-release
  namespace: openshift-pipelines
spec:
  params:
    - name: releaseversion
      value: $(body.release.tag_name)
    - name: gitrepositoryurl
      value: $(body.repository.url)
    - name: contenttype
      value: $(header.Content-Type)
    - name: action
      value: $(body.action)

---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-template-ieam-edge-pipeline-n9ybc1
  namespace: openshift-pipelines
spec:
  params:
    - name: releaseversion
    - name: gitrepositoryurl
    - name: contenttype
    - name: action
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: ieam-edge-pipeline-
        labels:
          tekton.dev/pipeline: ieam-edge-pipeline
        namespace: openshift-pipelines
      spec:
        params:
          - name: GIT_REPO
            value: >-
              https://github.com/Client-Engineering-Industry-Squad-1/ieam-edge-cluster-demo
          - name: GIT_REVISION
            value: main
          - name: IMAGE_BASE
            value: docker.io/appimage/ieam-edge-app
          - name: PATH_CONTEXT
            value: .
          - name: IMAGE_VERSION
            value: $(tt.params.releaseversion)
          - name: WEBHOOK_ACTION
            value: $(tt.params.action)
        pipelineRef:
          name: ieam-edge-pipeline
        resources: []
        status: null
        workspaces:
          - name: workspace
            persistentVolumeClaim:
              claimName: workspace-pvc
          - name: credentials
            secret:
              secretName: remote-ssh-secret
          - name: docker-registry
            secret:
              secretName: docker-registry


---

apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: event-listener-ieam-edge-pipeline
  namespace: openshift-pipelines
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: ClusterTriggerBinding
          ref: github-release
      template:
        ref: trigger-template-ieam-edge-pipeline-n9ybc1