## Append samples of your project ##
resources:
- demo_v1alpha1_nginx.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: nginxinc/nginx-unprivileged
  newName: docker.io/jennuinenes/ieam-edge-app
  newTag: latest
