---
- name: Install IEAM agent on OpenShift Edge cluster
  vars:
    HZN_EXCHANGE_USER_AUTH: ""
    HZN_ORG_ID: ""
    HZN_FSS_CSSURL: ""
    AGENT_NAMESPACE: ""
    EDGE_CLUSTER_STORAGE_CLASS: ""
  hosts: localhost
  tasks:
    - name: Expose image registry default route
      community.okd.k8s:
        state: absent
        api_version: v1
        kind: Service
        namespace: testing
        name: web